version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  prisma:
    container_name: prisma
    image: node:22
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npx prisma generate && npm run lint && npm run format && npm run dev"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  postgres_data:
