name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: blog
          POSTGRES_PASSWORD: password
          POSTGRES_DB: blog
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U blog"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: "postgresql://blog:password@localhost:5432/blog"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install playwright
        run: npx playwright install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run migrations
        run: npx prisma migrate dev --name init

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test